apiVersion: v1
kind: Secret
metadata:
  name: private-registry-secret
  namespace: default
data:
  .dockerconfigjson: "your docker registry credentials"
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: default
spec: 
  replicas: 3
  selector:
    matchLabels:
      lang: nodejs
  template:
    metadata:
      labels:
        lang: nodejs
    spec:
      containers:
        - name: nodejs-lb
          image: ghcr.io/haikalrfadhilahh/nodejs_k8s:latest
          ports:
            - containerPort: 2020
          resources:
            limits:
              cpu: '1'
              memory: '2048Mi'
      imagePullSecrets:
        - name: private-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec: 
  type: LoadBalancer
  selector:
    lang: nodejs
  ports:
    - port: 3030
      targetPort: 2020
      protocol: TCP
  # internal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: nodejs-service
            port:
              number: 3030
